#!/bin/bash
# Check that Champ_fonc_reprise gives same result than classic restart: 
trust reprise_PolyMAC_CDO.data 1>reprise_PolyMAC_CDO.out_err 2>&1 || exit -1
compare_lata_gz Champ_fonc_reprise_PolyMAC_CDO_xyz.lml reprise_PolyMAC_CDO.lml || exit -1
