#!/bin/bash

# Verification du fichier de decoupage sur veymont
if [ -f decoupage.metis ] && [ -f Cx.metis ]
then
   diff Cx.metis decoupage.metis 1>/dev/null 2>&1
   [ $? != 0 ] && echo "Metis partitionning has changed!" && exit -1
fi 

#####################################
# Comparaison non regression des .out
#####################################
message()
{
   [ $1 != $2 ] && echo $ECHO_OPTS "Error ($1!=$2) when checking:\n $msg" && err=1
   #[ $debog = 1 ] && echo $msg
}
err=0
for out in `ls Cx*.out.ref`
do
   msg="compare_sonde $out ${out%.ref}"
   eval $msg 1>verifie.log 2>&1
   message $? 0
done
[ $err != 0 ] && exit $err

########################################
# Comparaison de l'utilisation de la RAM avec $exec
# On verifie entre le premier pas de temps et le dernier
# pas de temps (initialization + postraitement pas pris en compte)
########################################
echo $ECHO_OPTS "Memory usage check for $1 ...\c"
ram_after_10dt=`grep "MBytes of RAM taken by the calculation" $1.out | tail -n 11 | head -1 | awk '/MBytes of RAM taken by the calculation/{print $1}'`
ram_at_1dt=`grep "MBytes of RAM taken by the calculation" $1.out | tail -n 2 | head -1 | awk '/MBytes of RAM taken by the calculation/{print $1}'`
[ $ram_after_10dt -gt $ram_at_1dt ] && echo "RAM is increasing from $ram_at_1dt to $ram_after_10dt" && exit 255
echo $ECHO_OPTS "ok ($ram_after_10dt  $ram_at_1dt)"



#######################################################
# Comparaison non regression des echange_espace_virtuel
#######################################################
# Verification du nombre d'appels a echange_espace_virtuel par pas de temps
if [ "${1#PAR_}" != "$1" ]
then
   echo $ECHO_OPTS "Number of calls to echange_espace_virtuel check for $1 ...\c"
   nb_max_echgs=24 && [ $exec != "$exec_opt" ] && nb_max_echgs=31
   err=`awk -v nb_max=$nb_max_echgs '/Number of virtual exchanges per time step:/ {if ($NF<nb_max) print 0;else print 1}' PAR_Cx.TU`
   [ "$err" = "0" ] && echo "OK (<$nb_max_echgs)" || echo "KO (>$nb_max_echgs)"
   exit $err
else
   exit 0
fi
